In [28]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Exercise 1

check the truthness of the following variables/values: 
(try to guess first)

- ""
- 0 -> zero
- []
- [0]
- ()

### Answer

---

### Exercise 2

Define a function that takes two values and compare them. the function should have shape like:
```python
which_one_is_bigger(a, b)
```
it returns a, if a is bigger than b, and b otherwise.

### Answer

---

### Exercise 3

Implement the following diagram.

![exercise3](flow_chart_ex3.png)

### Answer

---

### Exercise 4

In previous exercise (Exercise 3), we have if statement inside another if statement (two levels of conditional expressions). Try to write a code with same functionality with one level of conditional statements.

### Answer

---

### Exercise 5

You are provided with an array. Prints the numbers in this array that are divisible to the given number, and their location in the array

In [95]:
my_array = np.random.randint(0, 21, (5, 5))
my_array

array([[ 5,  2,  3, 20,  4],
       [17,  0, 16,  1,  1],
       [11,  2,  6,  9, 20],
       [ 9,  3,  3,  1, 17],
       [ 0, 11,  5,  9,  4]])

### Answer

---

### Exercise 6

Initialize two random 1D arrays. And check if they have similar elements:
- How many elements are similar?
- What are the similar elements?

### Answer

---

### Exercice 7

You are provided with two signals. you are required to:
- Find the period of intersections.

#### Extra 
- Plot a histogram of their intersection periods.

In [90]:
signal_1 = np.array(([0] * 5 + [1] * 5 + [0] * 5))
signal_2 = np.array(([0] * 3 + [1] * 5 + [0] * 7))
timing = np.linspace(0, 60, signal_1.size)

In [91]:
signal_1

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [92]:
signal_2

array([0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0])

In [93]:
timing

array([ 0.        ,  4.28571429,  8.57142857, 12.85714286, 17.14285714,
       21.42857143, 25.71428571, 30.        , 34.28571429, 38.57142857,
       42.85714286, 47.14285714, 51.42857143, 55.71428571, 60.        ])

### Answer

In [94]:
timing_intersect = timing[(signal_1==1) & (signal_2==1)]
timing_intersect[-1] - timing_intersect[0]

8.571428571428573

---

### Exercise 8

A die was tossed for 100000 times. You are provided with the result of all of these tosses (numbers between 1 and 6, inclusive). Please find the probablity of each possible outcome (e.g., if you were to toss it one more time, what is the possiblity it would be a specific number?).

In [75]:
result = np.random.randint(1,7,(100000,))

### Answer

In [76]:
frequency = []
for i in range(1,7):
    freq = np.sum(result == i)
    frequency.append(freq / len(result))

In [77]:
frequency

[0.16561, 0.16741, 0.16637, 0.16581, 0.16772, 0.16708]

### Exercise 9 - array manipulaton

---